import React from "react";
import type { Metadata } from "next";

import { Footer, Header, RoutesProtector, AuthProvider, StoreProvider } from "../components";

import "./globals.scss";
// import { TestProtector } from "../components";
// import { testRedirect } from "../components/_testProtector/actions/action";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode;
  // modalSignin: React.ReactNode;
  // modalSignup: React.ReactNode;
  modalAuth: React.ReactNode;
};

const RootLayout: React.FC<RootLayoutProps> = ({ children, modalAuth }) => {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <AuthProvider>
            <Header />
            <RoutesProtector>
              {children}
              {modalAuth}
              {/* {modalSignin}
              {modalSignup} */}
            </RoutesProtector>
            <Footer />
          </AuthProvider>
        </StoreProvider>
      </body>
    </html>
  );
};

export default RootLayout;
