import React from "react";
import type { Metadata } from "next";

import {
  Footer,
  Header,
  StoreTokenSetter,
  AuthProvider,
  StoreProvider,
  ResetProvider,
} from "../components";

import "./globals.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode;
  modalAuth: React.ReactNode;
};

const RootLayout: React.FC<RootLayoutProps> = ({ children, modalAuth }) => {
  return (
    <html lang="en">
      <body>
        <ResetProvider>
          <StoreProvider>
            <AuthProvider>
              <StoreTokenSetter />
              <Header />
              {children}
              {modalAuth}
              <Footer />
            </AuthProvider>
          </StoreProvider>
        </ResetProvider>
      </body>
    </html>
  );
};

export default RootLayout;
